# Generated by Django 5.2.4 on 2025-07-18 15:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('booking_success', 'Booking Success'), ('booking_rejected', 'Booking Rejected'), ('refund_request', 'Refund Request'), ('refund_processed', 'Refund Processed'), ('complaint_replied', 'Complaint Replied'), ('feedback_request', 'Feedback Request'), ('payment_approved', 'Payment Approved'), ('payment_rejected', 'Payment Rejected')], max_length=50)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_url', models.URLField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
