# Generated by Django 5.2.4 on 2025-07-18 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('history', models.TextField()),
                ('mission', models.TextField()),
                ('vision', models.TextField()),
                ('founders', models.TextField()),
                ('established_date', models.DateField()),
                ('location_description', models.TextField()),
                ('contact_info', models.TextField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AboutImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='about_images/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('is_featured', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('about_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='about.aboutpage')),
            ],
        ),
    ]
