# Generated by Django 5.2.4 on 2025-07-20 08:53

import about.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutimage',
            name='about_page',
        ),
        migrations.AlterModelOptions(
            name='aboutimage',
            options={'ordering': ['order', 'created_at']},
        ),
        migrations.RenameField(
            model_name='aboutimage',
            old_name='uploaded_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='aboutimage',
            name='is_featured',
        ),
        migrations.AddField(
            model_name='aboutimage',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='aboutimage',
            name='image',
            field=models.ImageField(upload_to=about.models.about_image_upload_path),
        ),
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='About Jaffna Cultural Centre', max_length=200)),
                ('subtitle', models.CharField(default='Preserving Culture Through Celebrations', max_length=300)),
                ('who_we_are_title', models.CharField(default='Who We Are', max_length=100)),
                ('who_we_are_description', models.TextField()),
                ('who_we_are_mission', models.TextField()),
                ('who_we_are_additional', models.TextField(blank=True)),
                ('who_we_are_image', models.ImageField(blank=True, null=True, upload_to=about.models.about_image_upload_path)),
                ('vision_title', models.CharField(default='Our Vision', max_length=100)),
                ('vision_description', models.TextField()),
                ('mission_title', models.CharField(default='Our Mission', max_length=100)),
                ('mission_description', models.TextField()),
                ('legacy_title', models.CharField(default='Our Legacy', max_length=100)),
                ('legacy_description', models.TextField()),
                ('establishment_year', models.IntegerField(default=1985)),
                ('events_hosted', models.IntegerField(default=5000)),
                ('happy_guests', models.IntegerField(default=50000)),
                ('years_of_excellence', models.IntegerField(default=38)),
                ('cta_title', models.CharField(default='Looking to Book a Venue?', max_length=200)),
                ('cta_subtitle', models.TextField(default='Experience the perfect blend of tradition and elegance for your special occasion')),
                ('cta_button_text', models.CharField(default='Explore Our Halls', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'About Us',
                'verbose_name_plural': 'About Us',
            },
        ),
        migrations.AddField(
            model_name='aboutimage',
            name='about_us',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='additional_images', to='about.aboutus'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='AboutPage',
        ),
    ]
