# Generated by Django 5.2.4 on 2025-07-21 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_remove_aboutimage_about_page_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='address',
            field=models.TextField(default='123 Cultural Street, Jaffna'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='email',
            field=models.EmailField(default='info@eventaura.lk', max_length=254),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='phone',
            field=models.CharField(default='+94 21 123 4567', max_length=20),
        ),
    ]
