# Generated by Django 5.2.4 on 2025-07-23 09:44

import django.db.models.deletion
import gallery.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_alter_gallerycategory_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('section_number', models.IntegerField(unique=True)),
                ('capacity', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='gallerycategory',
            options={'verbose_name_plural': 'Gallery Categories'},
        ),
        migrations.AlterModelOptions(
            name='galleryimage',
            options={'ordering': ['-upload_date']},
        ),
        migrations.RenameField(
            model_name='galleryimage',
            old_name='order',
            new_name='height',
        ),
        migrations.RenameField(
            model_name='galleryimage',
            old_name='uploaded_at',
            new_name='upload_date',
        ),
        migrations.RemoveField(
            model_name='gallerycategory',
            name='order',
        ),
        migrations.RemoveField(
            model_name='galleryimage',
            name='event_date',
        ),
        migrations.AddField(
            model_name='gallerycategory',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='alt_text',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='file_size',
            field=models.PositiveIntegerField(default=0, help_text='File size in bytes'),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='gallery/thumbnails/'),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='width',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gallerycategory',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='gallery.gallerycategory'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=models.ImageField(upload_to=gallery.models.gallery_image_path),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma separated tags', max_length=500),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='hall',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gallery_images', to='gallery.hall'),
        ),
    ]
