# Generated by Django 5.2.4 on 2025-08-14 14:16

import gallery.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_galleryimage_cloudinary_public_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galleryimage',
            name='uploaded_by',
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='cloudinary_thumbnail_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='cloudinary_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='cloudinary_public_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=gallery.models.gallery_image_path),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='gallery/thumbnails/'),
        ),
    ]
